@startuml
class 注文 {
  お名前
  電話番号
  注文日時
}

class 注文商品 {
  注文ID
  商品ID
}

class 商品 {
  名前
  値段
  商品ジャンルID
  New
}

class 商品グループ {
  名前
  値段
  商品ジャンルID
}

class 商品グループ商品 {
  商品グループID
  商品ID
}

class 商品ジャンル {
  名前
}

注文 "1" <-- "*" 注文商品
商品 "1" <-- "*" 注文商品
商品ジャンル "1" <-- "*" 商品
商品ジャンル "1" <-- "*" 商品グループ
商品グループ <-- 商品グループ商品
商品 <-- 商品グループ商品
@enduml